### ISSUE TITLE
listede olmaması gereken kayıtlar hakkında

### ISSUE THREAD

**Issue by washaqq** [alptekinsunnetci/rtbh#1]
Merhaba,

https://list.rtbh.com.tr/output.txt dosyasını Adguard Home da DNS Block List'e ekledikten sonra ubuntu sunucuların güncellenemediğini gördüm, sebebi ise security.ubuntu.com ve archive.ubuntu.com 'un kullandığı ip adreslerinin listede olmasıydı.

![image](https://github.com/user-attachments/assets/405e0f10-7280-4cd2-9dfe-0a7dce23114f)

![image](https://github.com/user-attachments/assets/afbfd613-3882-472a-b05d-e3de83ebce2a)

**Comment by alptekinsunnetci** [comment]
Merhaba @washaqq ,

RTBH, bildiğiniz üzere IP tabanlı bir sistemle çalışmaktadır.

security.ubuntu.com ve archive.ubuntu.com DNS'lerini çözümlerken hangi IP adreslerine yönlendirildiğinizi tespit etme imkanımız bulunmamaktadır. Eğer bu bilgiyi bizimle paylaşırsanız, ulaşmaya çalıştığınız IP adresinin neden listeye alındığını sizinle paylaşabilirim.


```
nslookup archive.ubuntu.com
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
Name:    archive.ubuntu.com
Addresses:  2620:2d:4002:1::102
          2620:2d:4002:1::101
          2620:2d:4000:1::101
          2620:2d:4000:1::102
          2620:2d:4002:1::103
          2620:2d:4000:1::103
          91.189.91.83
          91.189.91.82
          91.189.91.81
          185.125.190.83
          185.125.190.82
          185.125.190.81
```


```
nslookup security.ubuntu.com
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
Name:    security.ubuntu.com
Addresses:  2620:2d:4000:1::103
          2620:2d:4000:1::102
          2620:2d:4002:1::102
          2620:2d:4002:1::101
          2620:2d:4000:1::101
          2620:2d:4002:1::103
          91.189.91.82
          185.125.190.83
          91.189.91.83
          185.125.190.81
          91.189.91.81
          185.125.190.82
```

Şeklinde kontrol sağlandığında, ilgili DNS'in yanıt verdiği IP adreslerinin RTBH listesinde olmadığı görülmektedir.

İyi çalışmalar.

**Comment by washaqq** [comment]
Merhaba @alptekinsunnetci,

aşağıda ki görseller işinize yarayabilir. listede 1.189.91.82 ip adresi var ve Ubuntu'nun sunucu ip adreslerinin içerisinde 189.91 geçtiği için sanırım hepsini engelliyor, görünen o ki RTBH'yi ilgilendiren bir şey yok.

archive.ubuntu.com
![image](https://github.com/user-attachments/assets/9a8fd961-5c7f-42aa-b5f1-480bcd83466c)

security.ubuntu.com
![image](https://github.com/user-attachments/assets/3c8e8136-9578-4de6-9eb0-5328ace0c058)

İyi Çalışmalar.

**Comment by alptekinsunnetci** [comment]
Merhaba @washaqq ,

Belirtmiş olduğunuz IP adresi incelendiğinde global bir şekilde listelendiği referans görülmüştür.
[https://www.abuseipdb.com/check/1.189.91.82](https://www.abuseipdb.com/check/1.189.91.82)

Eğer kayıt benzerliğinden ötürü engelleme yaşanıyor ise, kullandığınız uygulamanın ayarlarını kontrol etmeniz gerekecektir.

İyi çalışmalar.
